theme: jekyll-theme-midnight

baseurl: ""

# GH-pages supported plugins
relative_links:
  enabled: true
  collections: true
  
gems:
  - jekyll-feed
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-relative-links